// Statyczne kroki na wypadek błędu sieci — gwarantuje że appka nie ucichnie
window.FALLBACK_STEPS = [
  {
    target: "Wielki Wóz",
    narration: "Popatrz na północ, gdzie niebo jest najciemniejsze i najbardziej spokojne. Szukaj siedmiu jasnych gwiazd, które razem tworzą piękny, wyrazisty kształt — dużą, solidną chochlę do zupy. To Wielki Wóz, zwany też Wielką Niedźwiedzicą — najjaśniejsza, najwartościowsza i najłatwiejsza do znalezienia część całego gwiazdozbioru. Cztery gwiazdy tworzą czę — ogromny, wyraźny kwadrat — a trzy pozostałe to długa, gracjojna rączka, która się zaokrągla. Od tysięcy lat ludzie na całym świecie patrzyli na ten gwiazdozbiór — Babilończycy, Grecy, Arabowie, Chińczycy. Są to najjaśniejsze gwiazdy na północnym niebie, widoczne przez cały rok, o każdej porze nocy. To twoja mapa na niebie, twój kompas, twój pierwszy punkt orientacyjny, który nigdy cię nie zawiedzie. Nazwy gwiazd pochodzą z arabskiego — Dubhe to Arab — brzask, a Merak to tyłek niedźwiedzicy. To jest legenda napisana w gwiazdach.",
    fact: "Dwie skrajne gwiazdy miski — jasna pomarańczowa Dubhe i jaśniejsza Merak — to naprawdę dwa niezawodne wskaźniki pokazujące drogę północy. Jeśli wyciągniesz linię od Meraka przez Duphę i wydłużysz ją około pięciokrotnie (tak daleko, jak od jednego końca Wozu do drugiego), poprowadzą cię wprost do Gwiazdy Polarnej, która prawie stoi w miejscu na nocnym niebie — jedynym punktem, wokół którego kręci się całe nocne niebo."
  },
  {
    target: "Gwiazda Polarna",
    narration: "Świetnie znalazłeś Wielki Wóz — to była najtrudniejsza część. Teraz będziemy nawigować za pomocą jego rączki — będzie to znacznie łatwiejsze, ale bardziej magiczne. Znajdź dwie gwiazdy na końcu miski — te, które wyglądają jak solidna, gruba wylewka chochli do zupy. Są to dwie najważniejsze gwiazdy Wozu. Górna to Dubhe — pomarańczowa, ciepła, stara gwiazda — nazwa pochodzi z arabskiego i oznacza brzask. Poniżej niej jest jaśniejsza Merak, której nazwa oznacza tyłek niedźwiedzicy. Teraz narysuj w myślach długą, precyzyjną linię od Meraka przez Duphę i wydłuż ją około pięciokrotnie — dokładnie tak daleko, jak od jednego końca Wozu do drugiego, czasami jeszcze trochę dalej. Ta magiczna linia poprowadzi cię prosto do samotnej gwiazdy, która zdaje się stać kompletnie, całkowicie w miejscu. Podczas gdy całe nocne niebo wiruje i obraca się wokół ciebie jak ogromny obracający się dysk, ona — jedyna gwiazda z miliardów — pozostaje nieruchoma, stała, niezmiennie w tym samym punkcie na niebie. To Gwiazda Polarna, zwana także Severką, Polarną, Północnicą, Alruccabą w arabskim. To królowa północy.",
    fact: "Od tysięcy lat — od czasów starożytnych Babilonów, przez fenickich żeglarzy wędrujących po Morzu Śródziemnym, przez arabskich astronomów, przez całe pokolenia Krzyżowców idących do Ziemi Świętej — ta jedna gwiazda wskazywała kierunek północny dla każdego, kto patrzył w niebo. Chrystof Kolumb stał na pokładzie swojego statku i patrzył na nią każdej nocy, zanim pół nocą popłynął na ocean znaleźć Nowy Świat. Polscy powstańcy uciekający przed carem trzymali jej wzrok. Niewolnicy uciekający przez Podziemną Kolej do wolności w Północnej Ameryce szli za nią. Całe nocne niebo obraca się wokół niej jak gigantyczne koło — każda inna gwiazda wędruje po niebie przez noc, ale ona zawsze pozostaje na swoim miejscu. Wokół niej kręci się cały biegun naszego świata. To jedyna gwiazda, która nie wędruje po niebie."
  },
  {
    target: "Kasjopeja",
    narration: "Doskonale znalazłeś Gwiazdę Polarną — jesteś już ekspertem w nawigacji! Teraz wracamy do naszego bezpiecznego, niezawodnego Wielkiego Wozu — to jest nasze kotwicze, nasze home base na niebie. Znowu popatrz na siedem gwiazd chochli. Widzisz tę samotną Gwiazdę Polarną, którą właśnie znaleźliśmy? Znajduje się gdzieś za twoją lewą ramię, jeśli patrzyłeś na północ w stronę Wozu. Po drugiej stronie Gwiazdy Polarnej — dokładnie naprzeciwko Wielkiego Wozu — czeka piękny następny gwiazdozbiór, który możemy znaleźć. Szukaj bardzo wyraźnego kształtu litery W lub litery M — to zależy od pory roku i od kąta, pod którym się na niego patrzysz. Pięć jasnych, jasnych gwiazd tworzy ten charakterystyczny, wyrazisty zygzak, jak gdyby ktoś napisał szybko na niebie. To Kasjopeja — jedna z najładniejszych, najmniej znanych grup gwiazd na nocnym niebie. Jej gwiazdy tworzą przepiękny, ostry, dramatyczny kształt — byle się nie pomylić, bo czasami wygląda zaraz jak litera N, czasami jak W.",
    fact: "W greckiej mitologii Kasjopeja to pycha i piękność wcielone w postać człowieka — była królową, która pochwalała się swoją piękością bardziej niż nimfy morskie, córki Posejdona. Za tę nieskończoną pycha została skazana przez bogów — musi siedzieć do góry nogami na tronie na niebie, wiecznie karana za swoją arogancję. Kiedy Gwiazda Polarna wzchodzi wysoko nad horyzontem i jest górna na niebie, Kasjopeja właśnie przechodzi tamtędy koło niej, odbijając się w tej kosmicznej karze. Polska ludowa nazwa tej gwiazdy to Ławka — co ma sens, bo siedzi na tronie."
  },
  {
    target: "Plejady",
    narration: "Świetnie! Już jesteś prawdziwym znawcą nieba. Wróćmy do naszego niezawodnego, bezpiecznego wskaźnika — Wielkiego Wozu, który zawsze nas prowadzi. Pamiętasz te siedem pięknych gwiazd chochli? Teraz spójrz poniżej jej długiej rączki — w stronę przeciwną od Gwiazdy Polarnej, poniżej. Szukaj małej, zbita, zwartej grupy bardzo bliskich sobie gwiazd, które razem tworzą kształt chmurki lub siedmiu małych, jasnych ziarenek, jak chmura rozporoszona na niebie. Nie są one jasne, błyszczące i dominujące jak Wóz czy Gwiazda Polarna, ale są niezwykle wyraźne i oryginalne — siedem czy osiem sióstr, móc być nawet dziewięć, trzymających się razem, jakby były jedną rodziną. To Plejady, najpiękniejszy, najdzielniejszy, najmniejszy i najuroczszy gwiazdozbiór na całym nocnym niebie. Polakom znane też jako Stogi czy Stożki — przypominają małe, zgromadzone stogi siana albo snopki zboża leżące w polu.",
    fact: "Te siedem sióstr — czy jest ich siedem, osiem czy nawet dziewięć — wszystkie narodziły się razem z tego samego ogromnego obłoku gazu i kurzu około sto do sto dwadzieścia milionów lat temu. To jeden z najmłodszych znanych skupień gwiazd we całej galaktyce — są dziećmi nieba. Za tysiące lat rozprzędzą się na wszystkie strony galaktyki w różnych kierunkach — każda pójdzie w swoją niezależną drogę, opuszczając swoją rodzinę. Ale teraz, w tym momencie w historii wszechświata, w tej chwili, w której ty stoisz i patrzysz, siostry Plejad są razem. Starożytne cywilizacje — od Greków przez Arabów, przez Polinezyjczyków, przez Chińczyków — znały te gwiazdy i opowiadały o nich piękne legendy. Dla Greków to były siedem córek Atlasa — dla Polinezyjczyków to były siedem sióstr. Wszyscy na Ziemi patrzyliśmy na ten sam gwiazdozbiór przez tysiące lat."
  }
];
